#!/bin/sh
# install.sh — register the web-resilience skills with Antigravity / Jetski.
#
# Jetski discovers plugins under ~/.gemini/config/plugins/<name>/. This script
# points that path at the checkout, so the installed plugin tracks the repo and
# `git pull` is the whole update story.
#
#   ./antigravity/install.sh            # symlink (default)
#   ./antigravity/install.sh --copy     # copy, for machines that police symlinks
#   ./antigravity/install.sh --uninstall
#
# The skills are NOT duplicated for the plugin: antigravity/skills is a
# relative symlink to the canonical ../skills, so there is exactly one copy of
# every SKILL.md in the repo.

set -eu

PLUGIN_NAME=web-resilience-plugin

resolve_dir() {
  target=$1
  while [ -L "$target" ]; do
    link=$(readlink "$target")
    case $link in
      /*) target=$link ;;
      *) target=$(dirname "$target")/$link ;;
    esac
  done
  (cd -P "$(dirname "$target")" && pwd)
}

PLUGIN_DIR=$(resolve_dir "$0")
REPO_ROOT=$(dirname "$PLUGIN_DIR")
CONFIG_DIR=${ANTIGRAVITY_CONFIG_DIR:-$HOME/.gemini/config}
TARGET="$CONFIG_DIR/plugins/$PLUGIN_NAME"

MODE=symlink
for arg in "$@"; do
  case $arg in
    --copy) MODE=copy ;;
    --uninstall) MODE=uninstall ;;
    --help | -h)
      sed -n '2,15p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "error: unknown option '$arg'" >&2
      exit 1
      ;;
  esac
done

remove_existing() {
  if [ -L "$TARGET" ] || [ -e "$TARGET" ]; then
    rm -rf "$TARGET"
    echo "removed existing $TARGET"
  fi
}

if [ "$MODE" = uninstall ]; then
  remove_existing
  echo "uninstalled $PLUGIN_NAME"
  exit 0
fi

mkdir -p "$CONFIG_DIR/plugins"
remove_existing

if [ "$MODE" = symlink ]; then
  ln -s "$PLUGIN_DIR" "$TARGET"
  echo "linked $TARGET -> $PLUGIN_DIR"
else
  # -L dereferences the skills/bin symlinks so the copy is self-contained...
  cp -RL "$PLUGIN_DIR/" "$TARGET"
  # ...except the harness itself, which stays in the checkout. Replace the
  # copied launcher with a shim that points back at it, so a copied plugin
  # cannot silently run a stale harness.
  cat >"$TARGET/bin/wr" <<EOF
#!/bin/sh
# Generated by antigravity/install.sh --copy.
# The harness is NOT copied; it is executed from the checkout below.
WEB_RESILIENCE_HOME="$REPO_ROOT"
export WEB_RESILIENCE_HOME
exec "$REPO_ROOT/bin/wr" "\$@"
EOF
  chmod +x "$TARGET/bin/wr"
  echo "copied $PLUGIN_DIR -> $TARGET (harness runs from $REPO_ROOT)"
fi

echo
echo "skills registered:"
for skill in "$TARGET"/skills/*/SKILL.md; do
  [ -e "$skill" ] || continue
  name=$(basename "$(dirname "$skill")")
  echo "  - $name"
done

echo
echo "verifying the harness can run here:"
if "$TARGET/bin/wr" doctor; then
  :
else
  echo
  echo "The plugin is installed, but the harness cannot run yet — see above." >&2
  exit 1
fi

echo
echo "Restart Antigravity (or start a new conversation) to pick up the plugin."
